import '../styles/globals.css'
import './components/Headeris'
export const metadata = {
  title: 'Home Inteligend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body>
          {children}
        
      </body>
    </html>
  )
}
