import '../styles/globals.css'
import Container from './components/Container'
import Navigation from './components/Navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container classis="container bg-b">
          
          <Navigation/>

          {children}

        </Container>
      </body>
    </html>
  )
}
