
import Container from '../components/Containers/Container';
import ContainerChild from '../components/Containers/ContainerChild';
import ImageCarrusel from '../components/carrusel/ImageCarrusel';
import Navigation from '../components/inputFormsContent/Navigation'

export const metadata = {
    title: 'Home Forms',
    description: 'Generated by create next app',
  }

export default function inputFormsLayout({children}){
    return(
        <Container classis="container bg-b">
          <div>
            <label className='txt-w w-20 txt-center title1 p-ab'>InteligentStore</label>
            <div className='nav-container-v'>
              <Navigation/>
            </div>
            

            <ContainerChild classis='containerchild'>
              <ImageCarrusel>
              </ImageCarrusel>
                {children}
            </ContainerChild>

          </div>
        </Container>
    );
}