
export const metadata = {
    title: 'Home Forms',
    description: 'Generated by create next app',
  }

export default function inputFormsLayout({children}){
    return(
        <>
            {children}
        </>
    );
}